# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------


#Header files
HEADERS += ./Base.h \
    ./CCanvas.h \
    ./ColorDef.h \
    ./Point2.h \
    ./Point3.h \
    ./GLRender.h \
    Sphere.h

#Source files
SOURCES += ./CCanvas.cpp \
    ./GLRender.cpp \
    ./main.cpp \
    Sphere.cpp

#Forms
FORMS += ./GLRender.ui
